<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6E75GLM" failures="1" tests="9" name="testCases.v1_page_id_components" time="3.787" errors="0" timestamp="2022-07-13T17:31:27 CEST" skipped="0">
  <testcase classname="testCases.v1_page_id_components" name="checkResponseBody" time="0.002"/>
  <system-out/>
  <testcase classname="testCases.v1_page_id_components" name="checkResponseTime" time="0.000"/>
  <system-out/>
  <testcase classname="testCases.v1_page_id_components" name="verifyPostRequiredFields" time="0.717"/>
  <system-out/>
  <testcase classname="testCases.v1_page_id_components" name="verifyPostIdIsUnique" time="0.744"/>
  <system-out/>
  <testcase classname="testCases.v1_page_id_components" name="verifyPostStatusCode" time="0.760"/>
  <system-out/>
  <testcase classname="testCases.v1_page_id_components" name="verifyPostStatusCategoryIsPredefined" time="0.765"/>
  <system-out/>
  <testcase classname="testCases.v1_page_id_components" name="verifyConnectionStatus" time="0.000">
    <failure message="expected [close] but found [keep-alive]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [close] but found [keep-alive]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testCases.v1_page_id_components.verifyConnectionStatus(v1_page_id_components.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyConnectionStatus -->
  <system-out/>
  <testcase classname="testCases.v1_page_id_components" name="ckeckStatusCode" time="0.001"/>
  <system-out/>
  <testcase classname="testCases.v1_page_id_components" name="verifyPostGrouping" time="0.798"/>
  <system-out/>
</testsuite> <!-- testCases.v1_page_id_components -->
